'format amd';

var files = [
  'codemirror',
  'codemirror/mode/meta',
  './detect-indent',
  './detect-mode',
  './load-share',
  './soft-nav'
]

var keymaps = ['emacs', 'sublime', 'vim']
files = files.concat(keymaps.map(function(keymap) {
  return 'codemirror/keymap/' + keymap
}))

var languages = [
  'apl',
  'asciiarmor',
  'asterisk',
  'brainfuck',
  'clike',
  'clojure',
  'cmake',
  'cobol',
  'coffeescript',
  'commonlisp',
  'css',
  'cypher',
  'd',
  'dart',
  'diff',
  'django',
  'dockerfile',
  'dtd',
  'dylan',
  'ebnf',
  'ecl',
  'eiffel',
  // 'elm',
  'erlang',
  'factor',
  'forth',
  'fortran',
  'gas',
  'gfm',
  'gherkin',
  'go',
  'groovy',
  'haml',
  'handlebars',
  'haskell',
  'haxe',
  'htmlembedded',
  'htmlmixed',
  'http',
  'idl',
  'jade',
  'javascript',
  'jinja2',
  'julia',
  'kotlin',
  'livescript',
  'lua',
  'markdown',
  'mathematica',
  'mirc',
  'mllike',
  'modelica',
  'mumps',
  'nginx',
  'ntriples',
  'octave',
  // 'oz',
  'pascal',
  'pegjs',
  'perl',
  'php',
  'pig',
  'properties',
  'puppet',
  'python',
  'q',
  'r',
  'rpm',
  'rst',
  'ruby',
  'rust',
  'sass',
  'scheme',
  'shell',
  'sieve',
  'slim',
  'smalltalk',
  'smarty',
  'solr',
  'soy',
  'sparql',
  'spreadsheet',
  'sql',
  'stex',
  'stylus',
  'swift',
  'tcl',
  'textile',
  'tiddlywiki',
  'tiki',
  'toml',
  'tornado',
  'troff',
  'ttcn',
  'turtle',
  'twig',
  'vb',
  'vbscript',
  'velocity',
  'verilog',
  'vhdl',
  // 'vue',
  'xml',
  'xquery',
  'z80'
]
files = files.concat(languages.map(function(language) {
  return 'codemirror/mode/' + language + '/' + language
}))

var themes = [
  '3024-day',
  '3024-night',
  'abcdef',
  'ambiance-mobile',
  'ambiance',
  'base16-dark',
  'base16-light',
  'blackboard',
  'cobalt',
  'colorforth',
  'dracula',
  'eclipse',
  'elegant',
  'erlang-dark',
  'icecoder',
  'lesser-dark',
  'liquibyte',
  'material',
  'mbo',
  'mdn-like',
  'midnight',
  'monokai',
  'neat',
  'neo',
  'night',
  'paraiso-dark',
  'paraiso-light',
  'pastel-on-dark',
  'rubyblue',
  'seti',
  'solarized',
  'the-matrix',
  'tomorrow-night-bright',
  'tomorrow-night-eighties',
  'ttcn',
  'twilight',
  'vibrant-ink',
  'xq-dark',
  'xq-light',
  'yeti',
  'zenburn'
]
files = files.concat(themes.map(function(theme) {
  return 'codemirror/theme/' + theme + '.css!'
}))

var addons = [
  'comment/comment',
  'comment/continuecomment',
  'dialog/dialog.css!',
  'dialog/dialog',
  'display/autorefresh',
  'display/fullscreen.css!',
  'display/fullscreen',
  'display/panel',
  'display/placeholder',
  'display/rulers',
  'edit/closebrackets',
  'edit/closetag',
  'edit/continuelist',
  'edit/matchbrackets',
  'edit/matchtags',
  'edit/trailingspace',
  'fold/brace-fold',
  'fold/comment-fold',
  'fold/foldcode',
  'fold/foldgutter.css!',
  'fold/foldgutter',
  'fold/indent-fold',
  'fold/markdown-fold',
  'fold/xml-fold',
  'hint/anyword-hint',
  'hint/css-hint',
  // 'hint/html-hint',
  'hint/javascript-hint',
  'hint/show-hint.css!',
  'hint/show-hint',
  'hint/sql-hint',
  'hint/xml-hint',
  'lint/coffeescript-lint',
  'lint/css-lint',
  // 'lint/html-lint',
  'lint/javascript-lint',
  'lint/json-lint',
  'lint/lint.css!',
  'lint/lint',
  'lint/yaml-lint',
  // 'merge/merge.css!',
  // 'merge/merge',
  'mode/loadmode',
  'mode/multiplex',
  'mode/overlay',
  'mode/simple',
  'scroll/annotatescrollbar',
  'scroll/scrollpastend',
  'scroll/simplescrollbars.css!',
  'scroll/simplescrollbars',
  'search/match-highlighter',
  'search/matchesonscrollbar.css!',
  'search/matchesonscrollbar',
  'search/search',
  'search/searchcursor',
  'selection/active-line',
  'selection/mark-selection',
  'selection/selection-pointer',
  'tern/tern.css!',
  'tern/tern',
  'tern/worker',
  'wrap/hardwrap'
]
files = files.concat(addons.map(function(addon) {
  return 'codemirror/addon/' + addon
}))

define(files, function(CodeMirror) {
  return CodeMirror
})
